config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root "lobby#index"
  get "/lobby", to: "lobby#index"
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  # Defines the root path route ("/")

  resource :session
  resources :passwords, param: :token

  resources :users

  get "/lobby", to: "lobby#index"
  post "/lobby/logout", to: "lobby#logout", as: :logout_lobby
  post "/lobby/horse_racing", to: "lobby#horse_racing", as: :horse_racing_lobby
  post "/lobby/roulette", to: "lobby#roulette", as: :roulette_lobby

  get "horse_race/race"
  get "horse_race/betting"

  get "roulette/roulette_board"

  post 'horse_race/debug_skip_to_race', to: 'horse_race#debug_skip_to_race', as: 'debug_skip_to_race'
  post 'horse_race/submit_bet', to: 'horse_race#submit_bet', as: 'submit_bet'
  post 'horse_race/resolve_race', to: 'horse_race#resolve_race', as: 'resolve_race'
  post 'roulette/submit_roulette_bet', to: 'roulette#submit_roulette_bet'
end

app/controllers/horse_race_controller.rb
# Controller for Horse Race Betting Game
class HorseRaceController < ApplicationController
  def initialize
    super
    @debug = false
  end

  def race
    @race_time_after_finish = 3000 # Wait 3s after the race is done
    @race_time = (Horse.maximum(:speed) * 1000) + @race_time_after_finish
  end

  def betting; end

  # Race is over, pay the money to winning wagers
  def resolve_race
    payout_wagers

    # Remove random horses every now and again to keep things fresh
    Horse.remove_random_horses

    Horse.create_new_horse

    redirect_to horse_race_betting_path
  end

  # Pay winning wagers then delete them all for the next race
  def payout_wagers
    user = Current.session.user
    winners = Horse.order(:speed).limit(3) # Get 1st, 2nd & 3rd place horses

    # Payout winning wagers
    winners.each.with_index(1) do |winner, place|
      Wager.where(horse_id: winner.id, user_id: user.id).select { |wager| wager.hits? place }.each(&:fufill)
    end

    Wager.where(user_id: user.id).destroy_all # Remove all wagers fufilled or otherwise
  end

  def submit_bet
    wager = create_wager(params)
    wager.save # add wager to database

    # puts "$#{Current.session.user.balance}"
    Current.session.user.balance -= wager.amount # remove money from the user's bankaccount
    Current.session.user.save # update user
    # puts "$#{Current.session.user.balance}"

    redirect_to horse_race_betting_path
  end

  def create_wager(params)
    user   = Current.session.user
    horse  = Horse.find(params[:horse])
    kind   = params[:kind].to_s
    amount = params[:amount].to_f
    puts "#{kind.to_s.capitalize} Bet of $#{format('%.2f', amount)} on '#{horse.name}'"

    Wager.new(user: user, horse: horse, amount: amount, kind: kind)
  end

  def debug_skip_to_race
    redirect_to horse_race_race_path
  end
end

app/views/horse_race/betting.html.erb
<%= stylesheet_link_tag 'horse_betting.css', media: 'all' %>

<style>
.race_start {
    width:100%;
    text-align: center;
    font-weight: bold;
    font-size: 30px;
}

.balance {
    width:100%;
    text-align: center;
    font-weight: bold;
    font-size: 30px;
}

.wager {
    padding: 10px;
}
</style>


<div class="race_start", id="raceStartTimer"></div>

<div class="balance"><%= "#{Current.session.user.username.capitalize}'s Balance: $#{Current.session.user.balance}" %></div>


<div id="main_betting_menu" class="container">
<% Horse.all.each do |horse| %>
    <%= render 'shared/horse_bet_container', horse: horse %>
<% end %>
</div>

<div class="wager">
<%= render 'shared/wager' %>
</div>

<% if @debug %>
    <%= form_with(url: debug_skip_to_race_path, method: :post, local: true) do |form| %>
        <%= submit_tag "Start Race (Debug)" %>
    <% end %>
<% end %>

<script>
  function timeLeft() {
      const now     = new Date();
      const seconds = now.getSeconds();
      const every   = 60000;

      return every - (seconds * 1000);
  }

  function updateRaceStartTimer() {
      raceStartTimer = document.getElementById('raceStartTimer');
      raceStartTimer.textContent = (timeLeft() / 1000) + "s before the race starts";
  }

  updateRaceStartTimer();

  // Redirect to race on the minute
  <% unless @debug %> // When debugging it's annoying to wait, so if debug is true we'll ignore this and include a button to start instead
  setTimeout(function() {
      window.location.href = "<%= url_for(controller: 'horse_race', action: 'race')%>";
  }, timeLeft());

  var interval = setInterval(updateRaceStartTimer, 1000);
  <% end %>
</script>

app/views/horse_race/race.html.erb
<head>
  <%= csrf_meta_tags %>
</head>

<style>
  .background {
      height: 200px;
  }

  .race_image {
      position: absolute;
      background-image: url('<%= asset_path "track.png" %>');
      animation-name: parallaxImage;
        animation-delay: 0s;
        animation-duration: 2s;
        animation-iteration-count: infinite;
        animation-timing-function: linear;

      left: 0px;
      width: 200%;
      height: 200px;
  }

  @keyframes parallaxImage {
      100% {transform: translateX(-400px);}
  }
</style>


<script>
  <% unless @debug %>
  // Redirect back to bet page after the race is done
  setInterval(function() {
      const csrfToken = document.querySelector('meta[name="csrf-token"]');
      fetch("<%= url_for(controller: 'horse_race', action: 'resolve_race') %>", {
	  method: 'POST',
	  headers: {
	      'Content-Type': 'application/x-www-form-urlencoded',
	      'X-CSRF-Token': csrfToken.getAttribute('content')
	  },
	  body: ""
      }).then(response => {
	  if(response.ok) {
	      window.location.href = response.url;
	  }
	  else {
	      console.error('Failed to post: ', response.statusText);
	  }
      });
  }, <%= @race_time %>);
  <% end %>

  <% Horse.order(:speed).each.with_index(1) do |horse, place| %>
      setTimeout(function() {
          var rankings = document.getElementById("rankings").getElementsByTagName("tbody")[0];

          var newRow = rankings.insertRow();

          var newHorse = newRow.insertCell(0);
          newHorse.textContent = "<%= horse.name %>";

          var newTime  = newRow.insertCell(1);
          newTime.textContent = "<%= format('%.2f', horse.speed) %>s";

          <% profit = Wager.select {|wager| wager.horse_id == horse.id}.map {|wager| (wager.hits? place) ? wager.payout : -wager.amount}.sum %>

	  var newProfit = newRow.insertCell(2);
	  <% if profit != 0 %>
	      newProfit.style.color = "<%= profit > 0 ? 'green' : 'red' %>";
	      newProfit.textContent = "$<%= format('%.2f', profit) %>";
	  <% end %>

      }, <%= horse.speed * 1000 %>);
  <% end %>
</script>


<div class="background">
    <div class="race_image"></div>
<% Horse.all.each_with_index do |horse, index| %>
    <%= render 'shared/horse_race', horse: horse, track_index: index %>
<% end %>


<% if @debug %>
    <%= button_to 'Return To Betting', {controller: 'horse_race', action: 'resolve_race'}, method: :post %>
<% end %>

</div>

<table id="rankings">
  <thead>
    <tr>
      <td>Horse</td>
      <td>Time</td>
      <td>Payout</td>
    </tr>
  </thead>
  <tbody>
  </tbody>
</table>