config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root "lobby#index"
  get "/lobby", to: "lobby#index"
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  # Defines the root path route ("/")

  resource :session
  resources :passwords, param: :token

  resources :users

  get "/lobby", to: "lobby#index"
  post "/lobby/logout", to: "lobby#logout", as: :logout_lobby
  post "/lobby/horse_racing", to: "lobby#horse_racing", as: :horse_racing_lobby
  post "/lobby/roulette", to: "lobby#roulette", as: :roulette_lobby

  get "horse_race/race"
  get "horse_race/betting"

  get "roulette/roulette_board"

  post 'horse_race/debug_skip_to_race', to: 'horse_race#debug_skip_to_race', as: 'debug_skip_to_race'
  post 'horse_race/submit_bet', to: 'horse_race#submit_bet', as: 'submit_bet'
  post 'horse_race/resolve_race', to: 'horse_race#resolve_race', as: 'resolve_race'
  post 'roulette/submit_roulette_bet', to: 'roulette#submit_roulette_bet'
end

app/views/shared/_chat.html.erb
<%= stylesheet_link_tag 'chat.css', media: 'all' %>

<div class="chat-div">
    <div class="chat-header">
    </div>
    <div class="chat-text" id="messages">
    </div>
    <div class="chat-footer">
        <%= form_with(url: chat_send_url, method: :post, local: true) do |form| %>
            <%= form.text_field :input_string, maxlength: 30, class: "chat-input" %>
        <%= form.submit "Send", class: "send-button" %>
        <% end %>
    </div>
</div>

app/views/shared/_horse_bet_container.html.erb
<div class="horse-bet-container">
  <%= render "shared/horse_bet_form_stylized", horse: horse, kind: :straight%>
</div>

app/views/shared/_horse_bet_form_bet_line.html.erb
<%= stylesheet_link_tag 'horse_betting.css', media: 'all' %>

<%= form_with(url: submit_bet_path, method: :post, local: true) do |form| %>
<%= form.hidden_field :kind,  value: kind %>
<% form.label horse.id, class: "bet_input" %>
<%= form.hidden_field :horse, value: horse.id %>
<%= number_field_tag :amount, nil, step: 0.01, in: 0..Current.session.user.balance, class: "bet_input" %>
<%= form.label "#{'%5.0f' % horse.odds(kind)}x", class: "bet_ratio_div" %>
<div class="place_button">
    <%= submit_tag "#{kind.to_s.capitalize} Bet", class: "place_button" %>
    <span class="tooltiptext"> <%= Wager.tooltip(kind) %> </span>
</div>
<% end %>

app/views/shared/_horse_bet_form_stylized.html.erb
<%= stylesheet_link_tag 'horse_betting.css', media: 'all' %>

<div class="horse_container">
    <div class="horse_name_div"><text class="horse_name"><%= horse.name %></text></div>
    <%= image_tag horse.image, :class => "horse_img" %>
    <div class="place_div">
        <%= render "shared/horse_bet_form_bet_line", horse: horse, kind: :place %>
    </div>
    <div class="straight_div">
        <%= render "shared/horse_bet_form_bet_line", horse: horse, kind: :straight %>
    </div>
    <div class="show_div">
        <%= render "shared/horse_bet_form_bet_line", horse: horse, kind: :show %>
    </div>
</div>

app/views/shared/_horse_race.html.erb
<style>
  #horse {
      width: 100px;
      height: 100px;
      position: absolute;
      margin-top: 40px;
      animation-delay: 3s; /* 3..2..1..GO! */
  }

  @keyframes moveImage {
      0%   {left:   0%;}
      100% {left: 90%;}
  }

  @keyframes jostleImage {
      0%    { transform: rotate(15deg); }
      100%    { transform: rotate(-5deg); }
  }
</style>

<%= image_tag horse.image, id: "horse", style: "top: #{track_index * 15}px; animation: #{horse.animation}"%>

app/views/shared/_horse_winners_bar.html.erb
<style>
  .circle-image {
      border-radius: 50%;
      width: 150px;
      height: 150px;
      object-fit: cover;
      border: 5px solid #000;
      position: relative;
  }

  .overlay-number {
      position: absolute;
      bottom: 5px; /* Position from the bottom */
      right: 5px; /* Position from the right */
      background-color: rgba(0, 0, 0, 0.6); /* Semi-transparent background */
      color: white;
      padding: 5px;
      border-radius: 50%; /* Make the number background a circle */
      font-size: 14;
      width: 30px;
      height: 30px;
      display: flex;
      justify-content: center;
      align-items: center;
  }

</style>


<% Horse.order(speed: :desc).limit(3).each.with_index(1) do |horse, place| %>
    <%= image_tag horse.image, class: "circle-image" %>
    <div class="overlay-number"><%= 2 %></div>
<% end %>

app/views/shared/_wager.html.erb
<style>
  .wager-table {
      height: 400px;
      overflow-y: auto;
  }

  table {
      width: 100%;
      border-collapse: collapse;
  }

  th, td {
      border: 1px solid #000;
      padding 8px;
  }
</style>

<div class="wager-table">
<table>
  <tr>
    <th>Horse</th>
    <th>Kind</th>
    <th>Amount</th>
    <th>Odds</th>
    <th>Payout</th>
  </tr>
<% Wager.where(user_id: Current.session.user.id).each do |wager| %>
  <tr>
    <% horse  = Horse.find(wager.horse_id)
       name   = horse.name
       kind   = wager.kind.capitalize
       amount = format("%.2f", wager.amount)
       odds   = format("%.2f", horse.odds(wager.kind))
       payout = format("%.2f", wager.payout) %>
    <th><%= name %></th>
    <th><%= kind %></th>
    <th>$<%= amount %></th>
    <th><%= odds %>x</th>
    <th>$<%= payout %></th>
  </tr>
<% end %>
</table>
</div>