config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root "lobby#index"
  get "/lobby", to: "lobby#index"
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  # Defines the root path route ("/")

  resource :session
  resources :passwords, param: :token

  resources :users

  get "/lobby", to: "lobby#index"
  post "/lobby/logout", to: "lobby#logout", as: :logout_lobby
  post "/lobby/horse_racing", to: "lobby#horse_racing", as: :horse_racing_lobby
  post "/lobby/roulette", to: "lobby#roulette", as: :roulette_lobby

  get "horse_race/race"
  get "horse_race/betting"

  get "roulette/roulette_board"

  post 'horse_race/debug_skip_to_race', to: 'horse_race#debug_skip_to_race', as: 'debug_skip_to_race'
  post 'horse_race/submit_bet', to: 'horse_race#submit_bet', as: 'submit_bet'
  post 'horse_race/resolve_race', to: 'horse_race#resolve_race', as: 'resolve_race'
  post 'roulette/submit_roulette_bet', to: 'roulette#submit_roulette_bet'
end

app/controllers/lobby_controller.rb
# This class handles the logic for the lobby page
class LobbyController < ApplicationController
  allow_unauthenticated_access

  def index
    puts "A gambler has entered the casino lobby"
  end

  def logout
    flash[:notice] = "99% of gamblers quit before they win big, I see you're in the minority..."
  end

  # When the horse racing button is pressed, the user is redirected to that games page.
  def horse_racing
    flash[:notice] = "Bet on zoolander, he's my favourite!"
    redirect_to horse_race_betting_path
  end

  # When the roulette button is pressed, the user is redirected to the roulette board page
  def roulette
    flash[:notice] = "Put it all on red!"
    redirect_to roulette_roulette_board_path
  end
end

app/helpers/lobby_helper.rb
# This module acts to contain all the helpers that the lobby page needs.
module LobbyHelper
end

app/views/lobby/index.html.erb
<head>
<%= stylesheet_link_tag "lobby" %>
</head>
<body id="lobby-body">
    <header class = "lobby-header">
        <h1>Casino</h1>
    </header>
    <div id="carpet-div">
    </div>
    <main id="main-text" class="lobby-main">
        <p>
            Welcome to Casino! <br>
            We are currently under construction but feel free to enjoy some horse races while we finish up the rest.
        </p>
        
    </main>
    <div class="lobby-account-info">
        <%= button_to "Logout", session_path, method: :delete %>
    </div>

    <div class="lobby-game" id="horse-racing">
        <%= button_to "Horse Racing", horse_racing_lobby_path, method: :post, remote: true %>
    </div>
    <div class="lobby-game" id="roulette">
        <%= button_to "Roulette", roulette_lobby_path, method: :post, remote: true %>
    </div>
    <div class="lobby-game" id="slots">
        <button class="coming-soon">Slots</button>
    </div>

<body>